name: Feature request
description: Suggest an idea
title: '[Feature]: '
body:
  - type: dropdown
    id: mod
    attributes:
      label: 'Which mod is this report for:'
      options:
        - Buffer
        - SpiritBirds
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label:  Is your feature request related to a problem? Please describe.
      description: Please note that I will not be making any changes/edits to skills, changing activation of skills, or enabling skills.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
  - type: markdown
    attributes:
      value: >-
        ---

        <br>


        > __Note:__ Make sure to attach any screenshots or images that will help
        explain or show the chage.