name: Update Buffer
on:
  workflow_dispatch
  #push:
   # tags:
    #- '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Delete tag
      run: gh release delete Buffer --cleanup-tag -y
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        path: 'Buffer/'
        filename: 'Buffer.zip'
        exclusions: '*.md /Buffer/*.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Buffer.zip"
        allowUpdates: true
        tag: 'Buffer'
        body: 'Buffer Update - Check Commits for changelog'
        replacesArtifacts: true
        token: ${{ secrets.TOKEN }}
